openapi: 3.0.1
info:
  title: BankAPI
  description: API Definition of BankAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/bankapi
- url: https://localhost:8253/bankapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
